Simple recommender

In [26]:
import pandas as pd

metadata = pd.read_csv('movies_metadata.csv', low_memory=False)

metadata.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0

In [27]:
C = metadata['vote_average'].mean()
print(C)

5.618207215134184

In [28]:
m = metadata['vote_count'].quantile(0.90)
print(m)

160.0

In [29]:
q_movies = metadata.copy().loc[metadata['vote_count'] >= m]
q_movies.shape

(4555, 24)

In [30]:
metadata.shape

(45466, 24)

In [31]:
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [32]:
q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

In [34]:
q_movies = q_movies.sort_values('score', ascending=False)
q_movies[['title', 'vote_count', 'vote_average', 'score']].head(30)

,title,vote_count,vote_average,score
314,The Shawshank Redemption,8358.0,8.5,8.445869
834,The Godfather,6024.0,8.5,8.425439
10309,Dilwale Dulhania Le Jayenge,661.0,9.1,8.421453
12481,The Dark Knight,12269.0,8.3,8.265477
2843,Fight Club,9678.0,8.3,8.256385
292,Pulp Fiction,8670.0,8.3,8.251406
522,Schindler's List,4436.0,8.3,8.206639
23673,Whiplash,4376.0,8.3,8.205404
5481,Spirited Away,3968.0,8.3,8.196055
2211,Life Is Beautiful,3643.0,8.3,8.187171
1178,The Godfather: Part II,3418.0,8.3,8.180076
1152,One Flew Over the Cuckoo's Nest,3001.0,8.3,8.164256
351,Forrest Gump,8147.0,8.2,8.150272
1154,The Empire Strikes Back,5998.0,8.2,8.132919
1176,Psycho,2405.0,8.3,8.132715
18465,The Intouchables,5410.0,8.2,8.125837
40251,Your Name.,1030.0,8.5,8.112532
289,Leon: The Professional,4293.0,8.2,8.107234
3030,The Green Mile,4166.0,8.2,8.104511
1170,GoodFellas,3211.0,8.2,8.077459
2216,American History X,3120.0,8.2,8.074059
15480,Inception,14075.0,8.1,8.072105
22879,Interstellar,11187.0,8.1,8.065005
7000,The Lord of the Rings: The Return of the King,8226.0,8.1,8.052649
256,Star Wars,6778.0,8.1,8.042766
46,Se7en,5915.0,8.1,8.034636
1161,12 Angry Men,2130.0,8.2,8.019613
586,The Silence of the Lambs,4549.0,8.1,8.015675
9698,Howl's Moving Castle,2049.0,8.2,8.012998
2884,Princess Mononoke,2041.0,8.2,8.012319

Content-based Recommender

In [35]:
metadata['overview'].head

<bound method NDFrame.head of 0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
45461          Rising and falling between a man and woman.
45462    An artist struggles to finish his work while a...
45463    When one of her hits goes wrong, a professiona...
45464    In a small town live two brothers, one a minis...
45465    50 years after decriminalisation of homosexual...
Name: overview, Length: 45466, dtype: object>

In [43]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
metadata['overview'] = metadata['overview'].fillna('')
tfidf_matrix = tfidf.fit_transform(metadata['overview'])
tfidf_matrix.shape

(45466, 75827)

In [44]:
tfidf.get_feature_names_out()[5000:5010]

array(['avails', 'avaks', 'avalanche', 'avalanches', 'avallone', 'avalon',
       'avant', 'avanthika', 'avanti', 'avaracious'], dtype=object)

In [46]:
from sklearn.metrics.pairwise import linear_kernel
tfidf_matrix = tfidf_matrix.astype(np.float32)
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim.shape

(45466, 45466)

In [47]:
cosine_sim[1]

array([0.01504121, 1.        , 0.04681952, ..., 0.        , 0.02198641,
       0.00929411], shape=(45466,), dtype=float32)

In [48]:
indices = pd.Series(metadata.index, index=metadata['title']).drop_duplicates()
indices[:10]

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
Heat                           5
Sabrina                        6
Tom and Huck                   7
Sudden Death                   8
GoldenEye                      9
dtype: int64

In [51]:
def get_recommendations(title, cosine_sim=cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return metadata['title'].iloc[movie_indices]

get_recommendations('The Empire Strikes Back')

256                                         Star Wars
1167                               Return of the Jedi
30434                   The Star Wars Holiday Special
10069    Star Wars: Episode III - Revenge of the Sith
26555                    Star Wars: The Force Awakens
30904                        Robot Chicken: Star Wars
21587                               The Story of Luke
12163                                          Decoys
26887                                       The Grind
33161                                   The Boys Club
Name: title, dtype: object

In [52]:
get_recommendations('Avatar')

23630                       Beware of Pity
3657                     Project Moon Base
27481                      Gregory Go Boom
18002                The War of the Robots
15706                         The American
18444                            Apollo 18
16068                        Bloodbrothers
19943            Welcome to the Space Show
27512    Vengeance: The Story of Tony Cimo
35666        OSS 117: Mission for a Killer
Name: title, dtype: object