In [1]:
import os
for root, dirs, files in os.walk('/kaggle/input'):
    for filename in files:
        print(os.path.join(root, filename))

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
import pandas as pd

train_data = pd.read_csv("/kaggle/input/competitions/titanic/train.csv")
test_data = pd.read_csv("/kaggle/input/competitions/titanic/test.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]
features = ["Pclass", "Sex", "SibSp", "Parch"]

X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

X.head()

   Pclass  SibSp  Parch  Sex_female  Sex_male
0       3      1      0       False      True
1       1      1      0        True     False
2       3      0      0        True     False
3       1      1      0        True     False
4       3      0      0       False      True

In [4]:
features = ["Pclass", "Sex", "SibSp", "Parch", "Age", "Fare"]

X = train_data[features].copy()
X_test = test_data[features].copy()

X['Age'] = X['Age'].fillna(X['Age'].median())
X_test['Age'] = X_test['Age'].median()

X_test['Fare'] = X_test['Fare'].fillna(X_test['Fare'].median())

X = pd.get_dummies(X)
X_test = pd.get_dummies(X_test)

model = RandomForestClassifier(n_estimators=100, max_depth=7, random_state=1)
model.fit(X, y)

predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission_v2.csv', index=False)